// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package databaseApi

import (
	"time"
)

type Device struct {
	DeviceID   int64
	DeviceGuid string
	DeviceName string
}

type Metric struct {
	SnapshotID int64
	MetricID   int64
	DeviceID   int64
	Value      float64
}

type MetricLookup struct {
	MetricID int64
	Name     string
}

type SnapshotTime struct {
	SnapshotID            int64
	ClientUtcTime         time.Time
	ClientTimezoneMinutes int64
	ServerUtcTime         time.Time
	ServerTimezoneMinutes int64
}
