// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package databaseApi

import (
	"time"
)

type Device struct {
	DeviceID   int64
	DeviceName string
}

type Ram struct {
	RamID        int64
	DeviceID     int64
	Timestamp    time.Time
	Usage        float64
	Total        float64
	UsagePercent float64
}
